export type ApplicationErrorCode =
  | "FORBIDDEN"
  | "APPLICATION_CANDIDATE_NOT_FOUND"
  | "APPLICATION_VACANCY_NOT_FOUND"
  | "VACANCY_NOT_ACCEPTING_APPLICATIONS"
  | "INITIAL_STAGE_NOT_FOUND"
  | "PIPELINE_CONFIGURATION_ERROR"
  | "VACANCY_LOCATION_NOT_FOUND"
  | "APPLICATION_SOURCE_NOT_FOUND"
  | "APPLICATION_ALREADY_ACTIVE"
  | "APPLICATION_ALREADY_TERMINAL"
  | "APPLICATION_REPOSITORY_ERROR";

export type ApplicationError = {
  readonly code: ApplicationErrorCode;
  readonly message: string;
};
